#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop2
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        # show_sql: true System.out 에 하이버네이트 실행 SQL을 남긴다
#        format_sql: true #logger를 통해 하이버네이트 실행 SQL을 남긴다
#logging.level:
#  org.hibernate.SQL: debug
## org.hibernate.type: trace